# Generated by Django 5.1.3 on 2025-04-11 00:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_category'),
        ('webstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sellerwhatsappnumber',
            name='whatsapp_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Valor não pode ser menor que 1.')]),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Valor não pode ser menor que 1.')])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='webstore.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
    ]
