# Generated by Django 5.1.3 on 2025-04-11 01:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0002_order_alter_sellerwhatsappnumber_whatsapp_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Valor não pode ser menor que 1.')]),
        ),
    ]
