# Generated by Django 5.1.3 on 2025-04-11 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0003_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
