# Generated by Django 5.1.3 on 2024-12-12 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0001_initial'),
        ('products', '0006_delete_productinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inflow_products', to='products.product'),
        ),
    ]
