# Generated by Django 5.1.3 on 2024-12-19 01:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_sale_payment_method_delete_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='O preço deve ser maior que zero')]),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='O preço total deve ser maior que zero')]),
        ),
    ]
