# Generated by Django 5.1.3 on 2024-12-22 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_remove_paymentmethod_value_sale_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_name',
            field=models.CharField(choices=[('PIX', 'Pix'), ('CARTÃO', 'Credit_Card'), ('DINHEIRO', 'Cash')], max_length=10),
        ),
    ]
