# Generated by Django 5.1.3 on 2024-12-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_remove_sale_payment_method_paymentmethod_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_name',
            field=models.CharField(choices=[('PIX', 'PIX'), ('CARTÃO', 'CARTÃO'), ('DINHEIRO', 'DINHEIRO')], max_length=20),
        ),
    ]
