# Generated by Django 5.1.3 on 2024-12-24 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_paymentmethod_method_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='O valor deve ser maior que zero.')]),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='O preço total deve ser maior que zero.')]),
        ),
    ]
