# Generated by Django 5.1.3 on 2024-12-28 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_salereturn_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salereturn',
            name='sale',
        ),
    ]
