# Generated by Django 5.1.3 on 2024-12-29 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_name'),
        ('sales', '0015_remove_salereturn_sale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaleReturn',
            new_name='SaleItemReturn',
        ),
    ]
