# Generated by Django 5.1.3 on 2024-12-30 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_rename_salereturn_saleitemreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='sales.sale'),
        ),
    ]
