# Generated by Django 5.1.3 on 2025-04-03 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_product_image'),
        ('sales', '0018_saleitemreturn_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitemreturn',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='products.product'),
        ),
    ]
