# Generated by Django 5.1.3 on 2025-04-22 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_saleitemreturn_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleItemReturn',
        ),
    ]
