# Generated by Django 5.1.3 on 2024-12-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_created_at_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(default=0, max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
