# Generated by Django 5.1.3 on 2024-12-08 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productinventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductInventory',
        ),
    ]
