# Generated by Django 5.1.3 on 2025-04-05 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0012_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category'),
        ),
    ]
