# Generated by Django 5.1.3 on 2025-04-05 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0013_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category'),
        ),
    ]
